### ISSUE TITLE
background service

### ISSUE THREAD

**Issue by eilite** [snigle/corsaire#1]
When turning the app off, service stays active in notification bar. 

@snigle

**Comment by snigle** [comment]
it's the normal behaviour. We can't detect when the user force quit the application. If he press the back button it will stop the service.

**Comment by eilite** [comment]
Are you sure ? Check google map for example

**Comment by snigle** [comment]
Maybe that :
http://stackoverflow.com/questions/19568315/how-to-handle-code-when-app-is-killed-by-swiping-in-android?answertab=active#tab-top
