### ISSUE TITLE
Add favorite places

### ISSUE THREAD

**Issue by snigle** [snigle/corsaire#2]
Users want the possibility to save their favorite places. We need to implement this functionality.
We have to store the name of the place and its localization.

**Comment by snigle** [comment]
@matthieusb @eilite 
Have you already saved data of android App ? I just used SharedPreference Object to keep data. It can only store Parcable or String object (can jsonify ou serialize the object).
Do you have other ideas ? Or do you think SharedPreference do the job ?

**Comment by eilite** [comment]
I think SharedPreference is good enough, if you can serialize and deserialize your List of favorite places into a JSON String. Maybe using Jackson for this part would make it easier
